[package]
name = "TaskMaster"
version = "2.0.0"
edition = "2024"

[dependencies]
iced = "0.13.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
chrono = "0.4.38"

[profile.release]
opt-level = "s"
lto = "fat"
strip = "debuginfo"

[build-dependencies]
winres = "0.1"
